apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bXl1c2Vy                            #Base 64 Encoded
  mongo-password: bXlwYXNzd29yZA==                #Base 64 Encoded